version: "3"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: postgres
      POSTGRES_DB: grpc-demo-db
    ports:
      - 5432:5432