spring:
  datasource:
    username: postgres
    password: changeme
    url: jdbc:postgresql://localhost:5432/grpc-demo-db
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
