spring:
  datasource:
    username: postgres
    password: changeme
    url: jdbc:postgresql://localhost:5432/grpc-demo-db
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration,classpath:db/migration-local

  jpa:
    open-in-view: false

server:
    port : 8420 # different port than default because GrpcClientApplication runs on default port(8080).
# grpc: 
#     port: 6666